services:
  gt-workflows:
    container_name: gt-workflows-container
    build:
      context: .
      dockerfile: Containerfile
    ports:
      - "3011:3011"
      - "3010:3010"
    volumes:
      - ./data:/app/data
    environment:
      - GT_WORKFLOWS_PATH=/app/data/gt-workflows
      - GT_WF_AUTH=true
      - GT_WF_ADMIN_USER=admin
      - GT_WF_ADMIN_PASSWORD=admin
      - GT_WF_GUEST_USER=guest
      - GT_WF_GUEST_PASSWORD=guest